// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmMS4kFzHEwPavsRvryBHKYQyJzi_k1Bo',
    appId: '1:66991098648:web:2f9f6c6cef497c177a2c6d',
    messagingSenderId: '66991098648',
    projectId: 'gproject-a5926',
    authDomain: 'gproject-a5926.firebaseapp.com',
    storageBucket: 'gproject-a5926.appspot.com',
    measurementId: 'G-GS30J65NXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wrdTSpv-iocFePzEbqSSY-OkdE_3VXo',
    appId: '1:66991098648:android:437f326ffb04115a7a2c6d',
    messagingSenderId: '66991098648',
    projectId: 'gproject-a5926',
    storageBucket: 'gproject-a5926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9GOFNC3OjKecLZCnyHL9OG5bTEDtApo',
    appId: '1:66991098648:ios:21d5c28fcb2ab9527a2c6d',
    messagingSenderId: '66991098648',
    projectId: 'gproject-a5926',
    storageBucket: 'gproject-a5926.appspot.com',
    iosClientId: '66991098648-dr7kclg5m45p23s4eioh1jathou9uc2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh9GOFNC3OjKecLZCnyHL9OG5bTEDtApo',
    appId: '1:66991098648:ios:a2c038442fdd82af7a2c6d',
    messagingSenderId: '66991098648',
    projectId: 'gproject-a5926',
    storageBucket: 'gproject-a5926.appspot.com',
    iosClientId: '66991098648-1tefp7t0dph444bdga0g396pmf8qe1pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientJourney.RunnerTests',
  );
}
